version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ResumeIAC"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gvjj2lttelgo"
s3_prefix = "ResumeIAC"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
